apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimalapitestaks-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minimalapitestaks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5    
  template:
    metadata:
      labels:
        app: minimalapitestaks
    spec:
      #nodeSelector:
      #  "kubernetes.io/os": linux
      containers:
      - name: minimalapitestaks
        image: acrdouglasgomes.azurecr.io/minimalapitestaks:v0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: minimalapitestaks
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: minimalapitestaks
